import { jsPDF } from "jspdf"
import pptxgen from "pptxgenjs"

export interface SlideData {
  title: string
  content: string
  layout: "title" | "content" | "two-column" | "image-right"
}

export async function exportToPowerPoint(slides: SlideData[], title: string, template: string) {
  const prs = new pptxgen.PresentationEx()
  prs.defineLayout({ name: "MASTER", width: 10, height: 7.5 })

  // Color scheme based on template
  const colorSchemes: Record<string, { primary: string; accent: string }> = {
    glamour: { primary: "F59E0B", accent: "DC2626" },
    cerulean: { primary: "3B82F6", accent: "0284C7" },
    emerald: { primary: "10B981", accent: "059669" },
    amethyst: { primary: "A855F7", accent: "7C3AED" },
    coral: { primary: "F87171", accent: "EF4444" },
    slate: { primary: "64748B", accent: "475569" },
  }

  const colors = colorSchemes[template] || colorSchemes.cerulean

  // Title slide
  const titleSlide = prs.addSlide()
  titleSlide.background = { color: "1E293B" }
  titleSlide.addText(title, {
    x: 0.5,
    y: 2.5,
    w: 9,
    h: 1.5,
    fontSize: 54,
    bold: true,
    color: "FFFFFF",
    align: "center",
  })
  titleSlide.addText("Professional Presentation Generated by AI", {
    x: 0.5,
    y: 4.2,
    w: 9,
    h: 0.8,
    fontSize: 24,
    color: colors.primary,
    align: "center",
  })

  // Content slides
  slides.forEach((slide, index) => {
    const contentSlide = prs.addSlide()
    contentSlide.background = { color: "1E293B" }

    // Header with accent bar
    contentSlide.addShape(prs.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 10,
      h: 0.1,
      fill: { color: colors.primary },
      line: { type: "none" },
    })

    // Slide number
    contentSlide.addText(`${index + 1}`, {
      x: 9,
      y: 6.8,
      w: 0.8,
      h: 0.5,
      fontSize: 12,
      color: "94A3B8",
      align: "right",
    })

    // Title
    contentSlide.addText(slide.title, {
      x: 0.5,
      y: 0.4,
      w: 9,
      h: 0.8,
      fontSize: 40,
      bold: true,
      color: colors.primary,
    })

    // Content
    contentSlide.addText(slide.content, {
      x: 0.5,
      y: 1.5,
      w: 9,
      h: 5.5,
      fontSize: 18,
      color: "E2E8F0",
      valign: "top",
      wrap: true,
    })
  })

  prs.writeFile({ fileName: `${title}.pptx` })
}

export async function exportToPDF(slides: SlideData[], title: string) {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "in",
    format: "letter",
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()

  // Title page
  doc.setFillColor(30, 41, 59)
  doc.rect(0, 0, pageWidth, pageHeight, "F")

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(40)
  doc.text(title, pageWidth / 2, pageHeight / 2 - 1, { align: "center" })

  doc.setFontSize(18)
  doc.setTextColor(147, 163, 184)
  doc.text("Professional Presentation", pageWidth / 2, pageHeight / 2 + 1, {
    align: "center",
  })

  // Content pages
  slides.forEach((slide) => {
    doc.addPage()
    doc.setFillColor(30, 41, 59)
    doc.rect(0, 0, pageWidth, pageHeight, "F")

    doc.setTextColor(59, 130, 246)
    doc.setFontSize(28)
    doc.text(slide.title, 0.5, 0.8)

    doc.setTextColor(226, 232, 240)
    doc.setFontSize(12)
    const splitContent = doc.splitTextToSize(slide.content, pageWidth - 1)
    doc.text(splitContent, 0.5, 1.5)
  })

  doc.save(`${title}.pdf`)
}

export async function exportToGoogleSlides(slides: SlideData[], title: string) {
  // This requires OAuth integration with Google Drive
  // For now, we'll create a format that can be imported
  const slideData = {
    title,
    slides: slides.map((slide) => ({
      title: slide.title,
      content: slide.content,
      layout: slide.layout,
    })),
  }

  const dataStr = JSON.stringify(slideData, null, 2)
  const dataBlob = new Blob([dataStr], { type: "application/json" })
  const url = URL.createObjectURL(dataBlob)
  const link = document.createElement("a")
  link.href = url
  link.download = `${title}-slides.json`
  link.click()
  URL.revokeObjectURL(url)

  alert(
    "Google Slides export data has been downloaded. You can import this into Google Slides to create a new presentation.",
  )
}

export async function exportToGoogleDrive(slides: SlideData[], title: string) {
  // This requires OAuth integration with Google Drive
  alert("Google Drive integration requires setup. Please use PowerPoint or PDF export.")
}
